// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using microwave_benner.Infra.Data.Context;

#nullable disable

namespace microwave_benner.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240906233125_create_heating_program")]
    partial class create_heating_program
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("microwave_benner.Domain.Entities.HeatingProgram", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("custom")
                        .HasColumnType("boolean");

                    b.Property<string>("food")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<char>("heatingChar")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.Property<string>("instructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("power")
                        .HasColumnType("integer");

                    b.Property<int>("time")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("heatingPrograms", (string)null);
                });

            modelBuilder.Entity("microwave_benner.Domain.Entities.HeatingTask", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("endTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("heatingProgramId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("pauseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("power")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("startTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("time")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("heatingProgramId");

                    b.ToTable("heatingTasks", (string)null);
                });

            modelBuilder.Entity("microwave_benner.Domain.Entities.HeatingTask", b =>
                {
                    b.HasOne("microwave_benner.Domain.Entities.HeatingProgram", "heatingProgram")
                        .WithMany()
                        .HasForeignKey("heatingProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("heatingProgram");
                });
#pragma warning restore 612, 618
        }
    }
}
