// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using microwave_benner.Infra.Data.Context;

#nullable disable

namespace microwave_benner.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240906000617_initial_migration")]
    partial class initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("microwave_benner.Domain.Entities.HeatingTask", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("endTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("pauseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("power")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("startTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("time")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("heatingTasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
